run:
  concurrency: 4
  timeout: 5m
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - godot
    - goerr113
    - gofumpt
    - goheader
    - gosec
    - importas
    - loggercheck
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
