with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
packages:
  github.com/FotiadisM/mock-microservice/internal/services/book/v1/queries:
    interfaces:
      Querier:
