version: "3.4"
services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "auth_svc"
      POSTGRES_USER: "local_user"
      POSTGRES_PASSWORD: "local_pass"
    volumes:
      - pgvolume:/var/lib/postgresql/data
  postgres-dev:
    image: postgres:15.1-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "local"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpass"
    volumes:
      - pgvolume-dev:/var/lib/postgresql/data
volumes:
  pgvolume:
  pgvolume-dev:
