version: "3.4"
services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - pgvolume:/var/lib/postgresql/data
  postgres-dev:
    image: postgres:15.1-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - pgvolume-dev:/var/lib/postgresql/data
volumes:
  pgvolume:
  pgvolume-dev:
