version: "3.4"
services:
  postgres:
    image: postgres:15.1-alpine
    # ATTENTION
    # fsync=off, synchronous_commit=off and full_page_writes=off
    # gives us a major speed up during local development and testing (~30%),
    # however you should NEVER use these settings in PRODUCTION unless
    # you want to have CORRUPTED data.
    # DO NOT COPY/PASTE THIS BLINDLY.
    # YOU HAVE BEEN WARNED.
    # Apply some performance improvements to pg as these guarantees are not needed while running locally
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "auth_svc"
      POSTGRES_USER: "local_user"
      POSTGRES_PASSWORD: "local_pass"
    volumes:
      - pgvolume:/var/lib/postgresql/data
  postgres-dev:
    image: postgres:15.1-alpine
    # ATTENTION
    # fsync=off, synchronous_commit=off and full_page_writes=off
    # gives us a major speed up during local development and testing (~30%),
    # however you should NEVER use these settings in PRODUCTION unless
    # you want to have CORRUPTED data.
    # DO NOT COPY/PASTE THIS BLINDLY.
    # YOU HAVE BEEN WARNED.
    # Apply some performance improvements to pg as these guarantees are not needed while running locally
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "local"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpass"
    volumes:
      - pgvolume-dev:/var/lib/postgresql/data
volumes:
  # postgresql: declare a named volume to persist DB data
  pgvolume:
  pgvolume-dev:
