services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "local"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgvolume:/var/lib/postgresql/data

  postgres-dev:
    image: postgres:15.1-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "local"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgvolume-dev:/var/lib/postgresql/data

volumes:
  pgvolume:
  pgvolume-dev:
