services:
  redis:
    image: "redis:7-alpine"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_svc
    volumes:
      - pgvolume:/var/lib/postgresql/data

  postgres-dev:
    image: postgres:15.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_svc
    volumes:
      - pgvolume-dev:/var/lib/postgresql/data

volumes:
  redis-data:
  pgvolume:
  pgvolume-dev:
