version: "3"

tasks:
  fmt:
    desc: Format code.
    deps:
      - go:fmt
      - buf:fmt
      - sql:fmt

  lint:
    desc: Lint code.
    deps:
      - go:lint
      - buf:lint
      - sqlc:gen

  gen:
    desc: Generate code.
    deps:
      - go:gen
      - buf:gen
      - sql:gen

  test:
    desc: Run tests
    deps:
      - go:test

  go:fmt:
    desc: Format Go code.
    cmd: gofumpt -w .

  go:lint:
    desc: Lint Go code.
    cmds:
      - go vet ./...
      - golangci-lint run

  go:gen:
    desc: Generate Go code.
    cmd: go generate ./...

  go:test:
    desc: Test Go code.
    cmd: gotestsum --format pkgname-and-test-fails -- -race -count=1 ./...

  buf:fmt:
    desc: Format protobuf files.
    cmd: buf format -w

  buf:lint:
    desc: Lint protobuf files.
    cmd: buf lint ./api/proto

  buf:gen:
    desc: Generate code from protobuf files.
    cmd: buf generate ./api/proto

  sql:fmt:
    desc: Format sql code.
    cmd: sqlfluff format -d postgres

  sql:gen:
    desc: Generate DB schema structs and queries
    cmd: sqlc generate

  sql:migrate:
    desc: Run the DB migrations.
    cmd: atlas schema apply --env local
