services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.115.1
    ports:
      - 4317:4317
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml

  prometheus:
    image: prom/prometheus:v3.0.1
    ports:
      - 9090:9090
    command:
      [
        "--web.enable-otlp-receiver",
        "--config.file=/etc/prometheus/prometheus.yml",
      ]
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - 16686:16686
